on:
  push:
    branches: [$default-branch]
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 15]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install --ignore-scripts
      - run: npx lerna bootstrap --no-ci
      - run: npm test
      - run: npm run codecov
        if: matrix.node == 14
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm install
      - run: npm run lint
