on:
  push:
    branches: [main]
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18, 19]
        include:
          # use latest npm by default
          - npm-version: latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      # TODO: remove once node 14 is dropped
      - name: Upgrade to latest npm to support lockfile v2
        run: npm install -g npm@${{ matrix.npm-version }}
      - run: npm install
      - run: npm test
      - run: npm run codecov
        if: matrix.node == 19

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install
      - run: npm run lint

  # Verify npm package-lock.json files use lockfileVersion 2
  verify-package-lock-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for f in $(git ls-files "**package-lock.json")
          do
            lockfileVersion=$(jq ".lockfileVersion" $f)
            if [ $lockfileVersion -lt 2 ]
            then
              >&2 echo "package-lock.json files should have at least lockfileVersion 2, but $f has version $lockfileVersion"
              exit 1
            fi
          done
