on:
  push:
    branches: [main]
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: |
          node --version
          npm --version
      - run: npm install
      - run: npm test
      - name: Report Coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: npm run lint

  # Verify npm package-lock.json files use lockfileVersion 2
  verify-package-lock-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          for f in $(git ls-files "**package-lock.json")
          do
            lockfileVersion=$(jq ".lockfileVersion" $f)
            if [ $lockfileVersion -lt 2 ]
            then
              >&2 echo "package-lock.json files should have at least lockfileVersion 2, but $f has version $lockfileVersion"
              exit 1
            fi
          done
